### ISSUE TITLE
[IDEA] Add option to uncheck "Override Driver Info" for all entries in Entry List

### ISSUE THREAD

**Issue by RADMRelish86** [Stoolbend/acc-toolkit#9]

**Comment by Stoolbend** [comment]
The checkbox to lock it on for all drivers has been removed & replaced with All on/All off buttons at the bottom.
The idea being to add all your cars/drivers & then use the buttons to turn them all on or off.
![image](https://github.com/Stoolbend/acc-toolkit/assets/1040992/6972d014-7013-4728-8a9b-623acfdb5b5c)
Hope this helps

**Comment by RADMRelish86** [comment]
Awesome! Thanks mate
